# -*- coding: utf-8 -*-
"""accessingdictionary

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NMrhzv7ukL2j5Wa0V6zrPpon2sfllJY
"""

my_dict = {"name": "nagashree", "age": 18}


my_dict["city"] = "New York"


my_dict["age"] = 19


print(my_dict)