# -*- coding: utf-8 -*-
"""add&remove

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NMrhzv7ukL2j5Wa0V6zrPpon2sfllJY
"""

my_set = {1, 2, 3}


my_set.add(4)
my_set.update([5, 6])

print("Set after adding elements:", my_set)


my_set.remove(3)
my_set.discard(7)


print("Set after removing elements:", my_set)