# -*- coding: utf-8 -*-
"""armstrongnumbercheckfunction.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14zVAgFl1KrFPXEaT3W3U5QjqxTlKo-OJ
"""



def is_armstrong_number(number):

  num_str = str(number)
  num_digits = len(num_str)
  sum_of_powers = sum(int(digit)**num_digits for digit in num_str)
  return sum_of_powers == number


number = int(input("Enter a number: "))


if is_armstrong_number(number):
  print(f"{number} is an Armstrong number")
else:
  print(f"{number} is not an Armstrong number")