# -*- coding: utf-8 -*-
"""checkkeyindictiory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NMrhzv7ukL2j5Wa0V6zrPpon2sfllJY
"""

my_dict = {'name': 'Gemini', 'age': 30, 'city': 'Mountain View'}


key_to_check = 'age'


if key_to_check in my_dict:
    print(f"The key '{key_to_check}' exists in the dictionary.")
else:
    print(f"The key '{key_to_check}' does not exist in the dictionary.")