# -*- coding: utf-8 -*-
"""checkelement

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NMrhzv7ukL2j5Wa0V6zrPpon2sfllJY
"""

# Define the dictionary
my_dict = {'name': 'Gemini', 'age': 30, 'city': 'Mountain View'}

# Define the key to check
key_to_check = 'age'

# Check if the key exists in the dictionary
if key_to_check in my_dict:
    print(f"The key '{key_to_check}' exists in the dictionary.")
else:
    print(f"The key '{key_to_check}' does not exist in the dictionary.")

set1 = {1, 2, 3}
set2 = {3, 4, 5}



union_set = set1.union(set2)

print("Union:", union_set)



intersection_set = set1.intersection(set2)

print("Intersection:", intersection_set)


difference_set = set1.difference(set2)

print("Difference (set1 - set2):", difference_set)



difference_set2 = set2.difference(set1)

print("Difference (set2 - set1):", difference_set2)