# -*- coding: utf-8 -*-
"""classforbankbalance

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UsZedQJxY8AaKe7v-RFcNeRlVjMLMbsc
"""

class bank:
  def __init__(self, balance=0):
    self.balance=balance

  def invest(self, amount):
    self.balance += amount
    print(f"Current balance: {self.balance}")

  def withdraw(self, amount):
    if amount < self.balance:
      self.balance -= amount
    else:
      print("Insufficient balance")


my_bank = bank(1000)
my_bank.invest(500)
my_bank.withdraw(200)