# -*- coding: utf-8 -*-
"""convertlistset

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NMrhzv7ukL2j5Wa0V6zrPpon2sfllJY
"""

my_list = [1, 2, 2, 3, 4, 4, 5]  # Example list with duplicates

# Convert the list to a set
my_set = set(my_list)

# Print the set (duplicates removed)
print(my_set)