# -*- coding: utf-8 -*-
"""countspecificfile

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gaOsUluLE_hpzm3ecQUTgVzNdTchxg3A
"""

import re

def count_word_occurrences(file_path, target_word):
    """Counts how many times a specific word appears in a text file."""
    try:
        with open(file_path, 'r') as file:
            text = file.read()
            word_count = len(re.findall(rf'\b{target_word}\b', text, re.IGNORECASE))  # Case-insensitive
        return word_count
    except FileNotFoundError:
        print(f"Error: File '{file_path}' not found.")
        return -1
    except Exception as e:
        print(f"An error occurred: {e}")
        return -1

# Example usage:
file_path = "my_text_file.txt"  # Replace with your file path
target_word = "example"

occurrences = count_word_occurrences(file_path, target_word)
if occurrences != -1:
    print(f"The word '{target_word}' appears {occurrences} times in the file.")