# -*- coding: utf-8 -*-
"""creatasimpleclass.oop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wcs-smX1MXaaCuJ_M4rhs33LwaoxkWU6
"""

class Car:
    def __init__(self, brand, model):
        self.brand = brand
        self.model = model

    def display_info(self):
        print(f"Brand: {self.brand}, Model: {self.model}")


my_car = Car("Toyota", "Camry")

my_car.display_info()