# -*- coding: utf-8 -*-
"""defaultargumentfunction.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14zVAgFl1KrFPXEaT3W3U5QjqxTlKo-OJ
"""

def greet(name, greeting="i love you"):

  print(f"{greeting}, {name}!")


greet("sanjana")
greet("lonika", greeting="i love you")