# -*- coding: utf-8 -*-
"""dictiorycreation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NMrhzv7ukL2j5Wa0V6zrPpon2sfllJY
"""

my_dict = {"name": "nagashree", "age": 19, "city": "New York"}


my_dict = dict(name="nagashree", age=19, city="New York")


print(my_dict)