# -*- coding: utf-8 -*-
"""dictioryexample

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NMrhzv7ukL2j5Wa0V6zrPpon2sfllJY
"""

a={
"name":"naga",
"age":20
}
a

