# -*- coding: utf-8 -*-
"""encapsulation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-vW_HG4VGkpZfA1-CQB5CRDH4_VDY2Mn
"""

class BankAccount:
    def __init__(self, initial_balance=0):
        self.__balance = initial_balance  # Private attribute for balance

    def deposit(self, amount):
        if amount > 0:
            self.__balance += amount
            print(f"Deposited: ₹{amount:.2f}. New Balance: ₹{self.__balance:.2f}")
        else:
            print("Invalid deposit amount. Please enter a positive value.")

    def withdraw(self, amount):
        if 0 < amount <= self.__balance:
            self.__balance -= amount
            print(f"Withdrew: ₹{amount:.2f}. New Balance: ₹{self.__balance:.2f}")
        else:
            print("Invalid withdrawal amount or insufficient balance.")

    def get_balance(self):
        return self.__balance
# Create an account with an initial balance of ₹1000
account = BankAccount(1000)

# Deposit ₹500
account.deposit(500)

# Withdraw ₹200
account.withdraw(200)

# Check the balance
balance = account.get_balance()
print(f"Current Balance: ₹{balance:.2f}")