# -*- coding: utf-8 -*-
"""evenoroddfunction.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14zVAgFl1KrFPXEaT3W3U5QjqxTlKo-OJ
"""

def is_even_or_odd(number):

  if number % 2 == 0:
    return "Even"
  else:
    return "Odd"


number = int(input("Enter a number: "))


result = is_even_or_odd(number)


print(f"The number {number} is {result}.")