# -*- coding: utf-8 -*-
"""fibonaccigeneratorfunction.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14zVAgFl1KrFPXEaT3W3U5QjqxTlKo-OJ
"""

def fibonacci_generator(n):

  fibonacci_numbers = []
  a, b = 0, 1
  for _ in range(n):
    fibonacci_numbers.append(a)
    a, b = b, a + b
  return fibonacci_numbers


n = 10
fibonacci_sequence = fibonacci_generator(n)
print(fibonacci_sequence)