# -*- coding: utf-8 -*-
"""filtermapfunction.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VZV3Lh3jYKK1ysl0wtjJaVPCsxbwvKIW
"""

numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Filter out even numbers using filter() and a lambda function
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))

# Double each even number using map() and a lambda function
doubled_even_numbers = list(map(lambda x: x * 2, even_numbers))

# Print the results
print("Original list:", numbers)
print("Even numbers:", even_numbers)
print("Doubled even numbers:", doubled_even_numbers)