# -*- coding: utf-8 -*-
"""GCDfunction.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14zVAgFl1KrFPXEaT3W3U5QjqxTlKo-OJ
"""

def gcd(a, b):

  while b:
    a, b = b, a % b
  return a


num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))


result = gcd(num1, num2)


print(f"The GCD of {num1} and {num2} is {result}.")