# -*- coding: utf-8 -*-
"""iterationthougth

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NMrhzv7ukL2j5Wa0V6zrPpon2sfllJY
"""

my_dict = {"name": "nagashree", "age": 19, "city": "New York"}


for key, value in my_dict.items():
    print(f"Key: {key}, Value: {value}")


for key in my_dict:
    print(f"Key: {key}, Value: {my_dict[key]}")