# -*- coding: utf-8 -*-
"""lambdasoting.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VZV3Lh3jYKK1ysl0wtjJaVPCsxbwvKIW
"""

# Sample list of tuples
my_list = [('apple', 3), ('banana', 1), ('orange', 2)]

# Sort the list using a lambda function as the key
sorted_list = sorted(my_list, key=lambda item: item[1])

# Print the sorted list
print(sorted_list)  # Output: [('banana', 1), ('orange', 2), ('apple', 3)]