# -*- coding: utf-8 -*-
"""length&breadthofobject

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wcs-smX1MXaaCuJ_M4rhs33LwaoxkWU6
"""

import math
class shape:
  def area(self):
    pass
class Rectangle(shape):
  def __init__(self,length,breadth):
        self.length = length
        self.breadth = breadth
def area(self):
  return self.length * self.width
  class circle(shape):
    def __init__(self,radius):
              self.radius = radius
  def area(self):
    return math.pi * self.radius * self.radius
rectangle = Rectangle(5, 4)
print(rectangle.area())

my_circle = circle(3)
print(my_circle.area())