# -*- coding: utf-8 -*-
"""listreveral

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NMrhzv7ukL2j5Wa0V6zrPpon2sfllJY
"""

numbers = [5, 2, 8, 1, 9, 3]



numbers.reverse()
print("Reversed list (using reverse()):", numbers)


reversed_numbers = numbers[::-1]
print("Reversed list (using slicing):", reversed_numbers)