# -*- coding: utf-8 -*-
"""listappend&inset

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e2WFLAt6NZKFZg-NMkjHLbbUiVC4BY6F
"""

my_list = [1, 2, 3, 4, 5]


my_list.append(6)


my_list.insert(2, 7)

print(my_list)