# -*- coding: utf-8 -*-
"""listindex

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e2WFLAt6NZKFZg-NMkjHLbbUiVC4BY6F
"""

my_list = [10, 20, 30, 40, 50]

first_element = my_list[0]
last_element = my_list[-1]


middle_index = len(my_list) // 2
middle_element = my_list[middle_index]

print("First element:", first_element)
print("Last element:", last_element)
print("Middle element:", middle_element)