# -*- coding: utf-8 -*-
"""listcomprehension

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NMrhzv7ukL2j5Wa0V6zrPpon2sfllJY
"""

# Using list comprehension to generate squares
squares = [x**2 for x in range(1, 11)]

# Print the list of squares
print(squares)