# -*- coding: utf-8 -*-
"""listsoting

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NMrhzv7ukL2j5Wa0V6zrPpon2sfllJY
"""

numbers = [5, 2, 8, 1, 9, 3]

# Ascending Sort
ascending_numbers = sorted(numbers)
print("Ascending Order:", ascending_numbers)

# Descending Sort
descending_numbers = sorted(numbers, reverse=True)
print("Descending Order:", descending_numbers)