# -*- coding: utf-8 -*-
"""mathmodul.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m7I-GGuWkYAYjC6LCfvLvcZmZgaHRp7Y
"""

import math

number = 10

square_root = math.sqrt(number)
print(f"The square root of {number} is: {square_root}")


factorial = math.factorial(number)
print(f"The factorial of {number} is: {factorial}")


radians = math.radians(number)
sine = math.sin(radians)
print(f"The sine of {number} radians is: {sine}")