# -*- coding: utf-8 -*-
"""max&minlist

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NMrhzv7ukL2j5Wa0V6zrPpon2sfllJY
"""

def find_max_min(numbers):

    max_value = max(numbers)
    min_value = min(numbers)
    return max_value, min_value


numbers = [5, 2, 8, 1, 9, 3]
maximum, minimum = find_max_min(numbers)

print("Maximum value:", maximum)
print("Minimum value:", minimum)