# -*- coding: utf-8 -*-
"""mergigdictionaries

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NMrhzv7ukL2j5Wa0V6zrPpon2sfllJY
"""

dict1 = {"name": "nagashree", "age":19}
dict2 = {"city": "New York", "occupation": "Engineer"}

dict1.update(dict2)

print(dict1)