# -*- coding: utf-8 -*-
"""merginglist

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NMrhzv7ukL2j5Wa0V6zrPpon2sfllJY
"""

def merge_lists_remove_duplicates(list1, list2):

  merged_list = list(set(list1 + list2))
  return merged_list


list1 = [1, 2, 3, 4, 5]
list2 = [3, 4, 5, 6, 7]

merged_list = merge_lists_remove_duplicates(list1, list2)
print("Merged list without duplicates:", merged_list)