# -*- coding: utf-8 -*-
"""merg2file

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gaOsUluLE_hpzm3ecQUTgVzNdTchxg3A
"""

def merge_files(file1_path, file2_path, output_file_path):
    """Merges the contents of two text files into a new file."""
    try:
        with open(file1_path, 'r') as file1, open(file2_path, 'r') as file2, open(output_file_path, 'w') as outfile:
            outfile.write(file1.read())
            outfile.write(file2.read())
        print(f"Files '{file1_path}' and '{file2_path}' merged into '{output_file_path}' successfully.")
    except FileNotFoundError:
        print(f"Error: One or both input files not found.")
    except Exception as e:
        print(f"An error occurred: {e}")

# Example usage:
file1_path = "file1.txt"  # Replace with your first file path
file2_path = "file2.txt"  # Replace with your second file path
output_file_path = "merged_file.txt"  # Replace with your desired output file path

merge_files(file1_path, file2_path, output_file_path)