# -*- coding: utf-8 -*-
"""powerfunction.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14zVAgFl1KrFPXEaT3W3U5QjqxTlKo-OJ
"""



def power(base, exponent):

  if exponent == 0:
    return 1
  elif exponent < 0:
    return 1 / power(base, -exponent)
  else:
    return base * power(base, exponent - 1)


base = float(input("Enter the base: "))
exponent = int(input("Enter the exponent: "))


result = power(base, exponent)


print(f"{base} raised to the power of {exponent} is {result}")