# -*- coding: utf-8 -*-
"""randommodule.

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VZV3Lh3jYKK1ysl0wtjJaVPCsxbwvKIW
"""

import random

def generate_random_number(start, end):



  random_number = random.randint(start, end)
  return random_number


random_number = generate_random_number(1, 10)
print(f"The random number is: {random_number}")