# -*- coding: utf-8 -*-
"""readJsonfile

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gaOsUluLE_hpzm3ecQUTgVzNdTchxg3A
"""

import json

def read_json_file(file_path):
    """Reads and parses a JSON file and prints its contents."""
    try:
        with open(file_path, 'r') as json_file:
            data = json.load(json_file)
            print("JSON data:")
            print(json.dumps(data, indent=4))  # Print with indentation for readability
    except FileNotFoundError:
        print(f"Error: File '{file_path}' not found.")
    except json.JSONDecodeError:
        print(f"Error: Invalid JSON format in the file.")
    except Exception as e:
        print(f"An error occurred: {e}")

# Example usage:
file_path = "data.json"  # Replace with your JSON file path

read_json_file(file_path)