# -*- coding: utf-8 -*-
"""removepop

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NMrhzv7ukL2j5Wa0V6zrPpon2sfllJY
"""

my_list = [10, 20, 30, 40, 50]

# Remove the element with value 30 using remove()
my_list.remove(30)
print("List after removing 30 using remove():", my_list)

# Remove the element at index 2 (which is now 40) using pop()
removed_element = my_list.pop(2)
print("List after removing element at index 2 using pop():", my_list)
print("Removed element:", removed_element)