# -*- coding: utf-8 -*-
"""reversedstringfunction.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14zVAgFl1KrFPXEaT3W3U5QjqxTlKo-OJ
"""

def reverse_string(text):

  return text[::-1]


string_to_reverse = input("Enter a string: ")

reversed_string = reverse_string(string_to_reverse)

print(f"The reversed string is: {reversed_string}")