# -*- coding: utf-8 -*-
"""simplecalculatorfunction.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14zVAgFl1KrFPXEaT3W3U5QjqxTlKo-OJ
"""

def simple_calculator(num1, num2, operator):

  if operator == '+':
    return num1 + num2
  elif operator == '-':
    return num1 - num2
  elif operator == '*':
    return num1 * num2
  elif operator == '/':
    if num2 == 0:
      print("Error: Division by zero is not allowed.")
      return None
    return num1 / num2
  else:
    print("Error: Invalid operator.")
    return None


num1 = float(input("Enter the first number: "))
num2 = float(input("Enter the second number: "))
operator = input("Enter the operator (+, -, *, /): ")


result = simple_calculator(num1, num2, operator)
if result is not None:
  print("Result:", result)