# -*- coding: utf-8 -*-
"""stcomprehension

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NMrhzv7ukL2j5Wa0V6zrPpon2sfllJY
"""

student_data = {
    "nagashree": [85, 92, 78],
    "pooja": [90, 88, 95],
    "lonika": [76, 82, 89],
}


print(student_data)