# -*- coding: utf-8 -*-
"""stcomprehension

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NMrhzv7ukL2j5Wa0V6zrPpon2sfllJY
"""

# Using set comprehension to create a set of even numbers
even_numbers = {x for x in range(1, 11) if x % 2 == 0}

# Print the set
print(even_numbers)