# -*- coding: utf-8 -*-
"""tuplecreation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NMrhzv7ukL2j5Wa0V6zrPpon2sfllJY
"""

a=(1,6,7,4,3,2,9)
for i in a:
  print(a)

a=(1,6,7,4,3,9)
for i in a:
  print(a)
  a[0]