# -*- coding: utf-8 -*-
"""tupleconcation

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NMrhzv7ukL2j5Wa0V6zrPpon2sfllJY
"""

tuple1 = (1, 2, 3)
tuple2 = (4, 5, 6)


concatenated_tuple = tuple1 + tuple2


print(concatenated_tuple)  # Output: (1, 2, 3, 4, 5, 6)