# -*- coding: utf-8 -*-
"""tupleunpacking

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15NMrhzv7ukL2j5Wa0V6zrPpon2sfllJY
"""

my_tuple = (10, 20, 30)
a, b, c = my_tuple
print(a)
print(b)
print(c)