# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TANEte59_roqoO_en7aKgD26Yxa4ezKA
"""

print("hello world")
print("nagashree")

num1=int(input("enter the first number:"))
num2=int(input("enter the second number:"))
result=num1+num2
print("The sum is:",result)

a=int(input("ente a:"))
b=int(input("enter b:"))
f=int(input("enter c:"))
c=a+b
d=a*b
e=a/b
print("addition is:",c)
print("multipication:",d)
print("division:",e)

celsius=float(input("enter temperature in celsius:"))
fahrenheit=(celsius*9/5)+32
print("temperature in fahrenheit:",fahrenheit)

fahrenheit=float

n=int(input("enter the hight"))
m=int(input("enter the wight"))

print("bmi")