# -*- coding: utf-8 -*-
"""vowelsinstringfunction.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14zVAgFl1KrFPXEaT3W3U5QjqxTlKo-OJ
"""

def count_vowels(text):

  vowels = "aeiouAEIOU"
  vowel_count = 0
  for char in text:
    if char in vowels:
      vowel_count += 1
  return vowel_count


string_to_analyze = input("Enter a string: ")


vowel_count = count_vowels(string_to_analyze)

print(f"The number of vowels in the string is: {vowel_count}")