# -*- coding: utf-8 -*-
"""withstatementredfile

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gaOsUluLE_hpzm3ecQUTgVzNdTchxg3A
"""

def read_file_with_with(file_path):
    """Opens a file using the with statement to ensure proper closing."""
    try:
        with open(file_path, 'r') as file:
            file_content = file.read()
            # Process the file content here
            print("File content:")
            print(file_content)
    except FileNotFoundError:
        print(f"Error: File '{file_path}' not found.")
    except Exception as e:
        print(f"An error occurred: {e}")

# Example usage:
file_path = "my_file.txt"  # Replace with your file path

read_file_with_with(file_path)